# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deposit.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1590, 755)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Chekiang Sung")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Grid_Title = QtWidgets.QGridLayout()
        self.Grid_Title.setContentsMargins(0, -1, -1, -1)
        self.Grid_Title.setObjectName("Grid_Title")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("SetoFont")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Title.setFont(font)
        self.Title.setScaledContents(False)
        self.Title.setObjectName("Title")
        self.Grid_Title.addWidget(self.Title, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.Grid_Title)
        self.Grid_Detail = QtWidgets.QGridLayout()
        self.Grid_Detail.setObjectName("Grid_Detail")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Grid_Detail.addWidget(self.label_3, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Grid_Detail.addItem(spacerItem, 0, 2, 1, 1)
        self.Grid_Rate = QtWidgets.QGridLayout()
        self.Grid_Rate.setObjectName("Grid_Rate")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(30)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Grid_Rate.addWidget(self.label_5, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.LCD_Total = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.LCD_Total.setFont(font)
        self.LCD_Total.setDigitCount(10)
        self.LCD_Total.setProperty("value", 1.0)
        self.LCD_Total.setObjectName("LCD_Total")
        self.Grid_Rate.addWidget(self.LCD_Total, 0, 0, 1, 1)
        self.Grid_Rate.setColumnStretch(0, 1)
        self.Grid_Detail.addLayout(self.Grid_Rate, 0, 1, 1, 1)
        self.Grid_Detail.setColumnStretch(0, 1)
        self.Grid_Detail.setColumnStretch(1, 1)
        self.Grid_Detail.setColumnStretch(2, 2)
        self.verticalLayout.addLayout(self.Grid_Detail)
        self.Grid_Time = QtWidgets.QGridLayout()
        self.Grid_Time.setObjectName("Grid_Time")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Grid_Time.addItem(spacerItem1, 0, 0, 1, 1)
        self.Grid_Time.setColumnStretch(0, 1)
        self.verticalLayout.addLayout(self.Grid_Time)
        self.Grid_Group = QtWidgets.QGridLayout()
        self.Grid_Group.setObjectName("Grid_Group")
        self.L_Group = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(40)
        self.L_Group.setFont(font)
        self.L_Group.setObjectName("L_Group")
        self.Grid_Group.addWidget(self.L_Group, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.LE_Deposit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_Deposit.sizePolicy().hasHeightForWidth())
        self.LE_Deposit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.LE_Deposit.setFont(font)
        self.LE_Deposit.setObjectName("LE_Deposit")
        self.Grid_Group.addWidget(self.LE_Deposit, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Grid_Group.addItem(spacerItem2, 0, 2, 1, 1)
        self.Grid_Group.setColumnStretch(0, 1)
        self.Grid_Group.setColumnStretch(1, 1)
        self.Grid_Group.setColumnStretch(2, 2)
        self.verticalLayout.addLayout(self.Grid_Group)
        spacerItem3 = QtWidgets.QSpacerItem(40, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.Grid_Button = QtWidgets.QGridLayout()
        self.Grid_Button.setObjectName("Grid_Button")
        self.BT_Confirm = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BT_Confirm.sizePolicy().hasHeightForWidth())
        self.BT_Confirm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.BT_Confirm.setFont(font)
        self.BT_Confirm.setObjectName("BT_Confirm")
        self.Grid_Button.addWidget(self.BT_Confirm, 0, 0, 1, 1)
        self.BT_Cancel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BT_Cancel.sizePolicy().hasHeightForWidth())
        self.BT_Cancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.BT_Cancel.setFont(font)
        self.BT_Cancel.setObjectName("BT_Cancel")
        self.Grid_Button.addWidget(self.BT_Cancel, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.Grid_Button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        self.Grid_Slogan = QtWidgets.QGridLayout()
        self.Grid_Slogan.setObjectName("Grid_Slogan")
        self.L_Slogan = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_Slogan.sizePolicy().hasHeightForWidth())
        self.L_Slogan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.L_Slogan.setFont(font)
        self.L_Slogan.setObjectName("L_Slogan")
        self.Grid_Slogan.addWidget(self.L_Slogan, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.Grid_Slogan)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 2)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 2)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1590, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "樂來樂生氣銀行"))
        self.label_3.setText(_translate("MainWindow", "目前帳戶"))
        self.label_5.setText(_translate("MainWindow", "萬元"))
        self.L_Group.setText(_translate("MainWindow", "預計存款"))
        self.BT_Confirm.setText(_translate("MainWindow", "確認CONFIRM"))
        self.BT_Cancel.setText(_translate("MainWindow", "取消CANCEL"))
        self.L_Slogan.setText(_translate("MainWindow", "一 時 存 錢 一 時 爽 ， 一 直 存 錢 一 直 爽 ， 錢 多 就 比 誰 更 浪 ， 身 價 翻 倍 紅 不 讓"))

