# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1590, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Chekiang Sung")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Grid_Title = QtWidgets.QGridLayout()
        self.Grid_Title.setContentsMargins(0, -1, -1, -1)
        self.Grid_Title.setObjectName("Grid_Title")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("SetoFont")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Title.setFont(font)
        self.Title.setScaledContents(False)
        self.Title.setObjectName("Title")
        self.Grid_Title.addWidget(self.Title, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.Grid_Title)
        self.Grid_Detail = QtWidgets.QGridLayout()
        self.Grid_Detail.setObjectName("Grid_Detail")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Grid_Detail.addWidget(self.label_3, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Grid_Length = QtWidgets.QGridLayout()
        self.Grid_Length.setObjectName("Grid_Length")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(30)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Grid_Length.addWidget(self.label_4, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Grid_Length.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.LCD_Length = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.LCD_Length.setFont(font)
        self.LCD_Length.setSmallDecimalPoint(True)
        self.LCD_Length.setDigitCount(1)
        self.LCD_Length.setProperty("value", 5.0)
        self.LCD_Length.setObjectName("LCD_Length")
        self.Grid_Length.addWidget(self.LCD_Length, 0, 1, 1, 1)
        self.Grid_Length.setColumnStretch(0, 1)
        self.Grid_Length.setColumnStretch(1, 1)
        self.Grid_Length.setColumnStretch(2, 1)
        self.Grid_Length.setRowStretch(0, 1)
        self.Grid_Detail.addLayout(self.Grid_Length, 0, 1, 1, 1)
        self.Grid_Rate = QtWidgets.QGridLayout()
        self.Grid_Rate.setObjectName("Grid_Rate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Grid_Rate.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.LCD_Interest_Rate = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(50)
        self.LCD_Interest_Rate.setFont(font)
        self.LCD_Interest_Rate.setDigitCount(1)
        self.LCD_Interest_Rate.setProperty("value", 1.0)
        self.LCD_Interest_Rate.setObjectName("LCD_Interest_Rate")
        self.Grid_Rate.addWidget(self.LCD_Interest_Rate, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(30)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Grid_Rate.addWidget(self.label_5, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.Grid_Rate.setColumnStretch(0, 1)
        self.Grid_Rate.setColumnStretch(1, 1)
        self.Grid_Rate.setColumnStretch(2, 1)
        self.Grid_Detail.addLayout(self.Grid_Rate, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Grid_Detail.addItem(spacerItem, 0, 3, 1, 1)
        self.Grid_Detail.setColumnStretch(0, 1)
        self.Grid_Detail.setColumnStretch(1, 1)
        self.Grid_Detail.setColumnStretch(2, 1)
        self.Grid_Detail.setColumnStretch(3, 2)
        self.verticalLayout.addLayout(self.Grid_Detail)
        self.Grid_Time = QtWidgets.QGridLayout()
        self.Grid_Time.setObjectName("Grid_Time")
        self.L_Time = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(40)
        self.L_Time.setFont(font)
        self.L_Time.setObjectName("L_Time")
        self.Grid_Time.addWidget(self.L_Time, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.LCD_Time = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_Time.setDigitCount(8)
        self.LCD_Time.setProperty("value", 11022033.0)
        self.LCD_Time.setProperty("intValue", 11022033)
        self.LCD_Time.setObjectName("LCD_Time")
        self.Grid_Time.addWidget(self.LCD_Time, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Grid_Time.addItem(spacerItem1, 0, 2, 1, 1)
        self.Grid_Time.setColumnStretch(0, 1)
        self.Grid_Time.setColumnStretch(1, 1)
        self.Grid_Time.setColumnStretch(2, 3)
        self.verticalLayout.addLayout(self.Grid_Time)
        self.Grid_Group = QtWidgets.QGridLayout()
        self.Grid_Group.setObjectName("Grid_Group")
        self.L_Group = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(40)
        self.L_Group.setFont(font)
        self.L_Group.setObjectName("L_Group")
        self.Grid_Group.addWidget(self.L_Group, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.LE_Group = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_Group.sizePolicy().hasHeightForWidth())
        self.LE_Group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.LE_Group.setFont(font)
        self.LE_Group.setObjectName("LE_Group")
        self.Grid_Group.addWidget(self.LE_Group, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Grid_Group.addItem(spacerItem2, 0, 2, 1, 1)
        self.Grid_Group.setColumnStretch(0, 1)
        self.Grid_Group.setColumnStretch(1, 1)
        self.Grid_Group.setColumnStretch(2, 3)
        self.verticalLayout.addLayout(self.Grid_Group)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.L_Serve = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(40)
        self.L_Serve.setFont(font)
        self.L_Serve.setObjectName("L_Serve")
        self.horizontalLayout.addWidget(self.L_Serve, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Grid_Button = QtWidgets.QGridLayout()
        self.Grid_Button.setObjectName("Grid_Button")
        self.BT_Deposit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BT_Deposit.sizePolicy().hasHeightForWidth())
        self.BT_Deposit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.BT_Deposit.setFont(font)
        self.BT_Deposit.setObjectName("BT_Deposit")
        self.Grid_Button.addWidget(self.BT_Deposit, 0, 2, 1, 1)
        self.BT_WithDrawal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BT_WithDrawal.sizePolicy().hasHeightForWidth())
        self.BT_WithDrawal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.BT_WithDrawal.setFont(font)
        self.BT_WithDrawal.setObjectName("BT_WithDrawal")
        self.Grid_Button.addWidget(self.BT_WithDrawal, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Grid_Button.addItem(spacerItem3, 0, 1, 1, 1)
        self.BT_AccountSearch = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.BT_AccountSearch.setFont(font)
        self.BT_AccountSearch.setObjectName("BT_AccountSearch")
        self.Grid_Button.addWidget(self.BT_AccountSearch, 0, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Grid_Button.addItem(spacerItem4, 0, 3, 1, 1)
        self.Grid_Button.setColumnStretch(0, 4)
        self.Grid_Button.setColumnStretch(1, 1)
        self.Grid_Button.setColumnStretch(2, 4)
        self.Grid_Button.setColumnStretch(3, 1)
        self.Grid_Button.setColumnStretch(4, 4)
        self.verticalLayout.addLayout(self.Grid_Button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.Grid_Slogan = QtWidgets.QGridLayout()
        self.Grid_Slogan.setObjectName("Grid_Slogan")
        self.L_Slogan = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_Slogan.sizePolicy().hasHeightForWidth())
        self.L_Slogan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.L_Slogan.setFont(font)
        self.L_Slogan.setObjectName("L_Slogan")
        self.Grid_Slogan.addWidget(self.L_Slogan, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.Grid_Slogan)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 4)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout.setStretch(5, 4)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 2)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1590, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "樂來樂生氣銀行"))
        self.label_3.setText(_translate("MainWindow", "本行利率"))
        self.label_4.setText(_translate("MainWindow", "分鐘"))
        self.label.setText(_translate("MainWindow", "存期"))
        self.label_2.setText(_translate("MainWindow", "利率"))
        self.label_5.setText(_translate("MainWindow", "%"))
        self.L_Time.setText(_translate("MainWindow", "現在時間"))
        self.L_Group.setText(_translate("MainWindow", "帳號"))
        self.L_Serve.setText(_translate("MainWindow", "請選擇服務項目"))
        self.BT_Deposit.setText(_translate("MainWindow", "帳戶存款 DEPOSIT"))
        self.BT_WithDrawal.setText(_translate("MainWindow", "帳戶提款 WITHDRAWAL"))
        self.BT_AccountSearch.setText(_translate("MainWindow", "餘額查詢 INQUIRY"))
        self.L_Slogan.setText(_translate("MainWindow", "一 時 存 錢 一 時 爽 ， 一 直 存 錢 一 直 爽 ， 錢 多 就 比 誰 更 浪 ， 身 價 翻 倍 紅 不 讓"))

